### PR TITLE
Handle file truncation and recreation

### PR DESCRIPTION
**Pull request by iaddict**
Try to handle file truncation or removal. This happens frequently on logfile rotation.

### CODE REVIEW

**Comment by TheFirstAvenger** [comment]
🎖❤️⭐️⚪️⭐️💙🎖

**Comment by TheFirstAvenger** [comment]
Going to do some cleanup on the project and push a new version shortly

**Comment by TheFirstAvenger** [comment]
v1.1.1 is now available. Let me know if you run into any issues with it.

**Comment by iaddict** [comment]
Already in production. Works fine so far. Many thanks to merge so fast :)

**Pull request merged**
